### ISSUE TITLE
NullPointerException when removing chat pattern

### ISSUE THREAD

**Issue by Xperthobbit** [joelamos/SourceRadio#7]
The program works great on TF2, but I get this error when testing on CSGO:

```
java.lang.NullPointerException
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.lang.String.replaceFirst(Unknown Source)
        at com.joelchristophel.sourceradio.LogReader.getChatSender(LogReader.java:158)
        at com.joelchristophel.sourceradio.LogReader.getInput(LogReader.java:142)
        at com.joelchristophel.sourceradio.LogReader.access$9(LogReader.java:122)
        at com.joelchristophel.sourceradio.LogReader$1.run(LogReader.java:78)
        at java.lang.Thread.run(Unknown)
```

This happens with any/every command and on Valve, community and local servers.
Screenshot:
![a061f486438d786cb965e0ac0ff2b668](https://cloud.githubusercontent.com/assets/13501615/17348020/a1b870f4-58e1-11e6-8dd2-ac8757523860.png)

**Comment by joelamos** [comment]
This issue has been fixed by commit 09030d9, but it's not part of the 2016.0802 release.

As a temporary fix until the next update, you can go into `SourceRadio\resources\strings\strings-ro.txt`, find the line starting with `terroristPattern` and insert `\` before the last `)`.

Let me know if this works.

**Comment by Xperthobbit** [comment]
I updated the line but I still receive the same error. 
This is what my `strings-ro.txt` looks like:
![4f176d9313a55fa65fdcb17292582f91](https://cloud.githubusercontent.com/assets/13501615/17352356/ffa69282-5903-11e6-9db9-b5365e3d5a63.png)

**Comment by joelamos** [comment]
Which language are you using?

**Comment by Xperthobbit** [comment]
Both are in english

**Comment by joelamos** [comment]
Does this problem occur whether you are on the Terrorist or Counter-Terrorist team?

**Comment by Xperthobbit** [comment]
It happens on both teams. And for some reason the !stop command works fine.

**Comment by joelamos** [comment]
What is the value of the `steam locale` property in `SourceRadio\properties\properties.txt`?

**Comment by Xperthobbit** [comment]
It is `en`

**Comment by joelamos** [comment]
This should be fixed by commit 17c2a0cace7675de0f1978c830b499d177eb7563, which is live in SourceRadio v2018.08.03
